### PR TITLE
Performance improvement

### PR DESCRIPTION
**Pull request by adon-at-work**
Increased the performance by around 20%

### CODE REVIEW

**Comment by adon-at-work** [comment]
@maditya, please review and merge.
you may like to use this for benchmarking. I got >0.65MB per second (and >1.8MB per second w/o c14n) using my 11" macbook air.

c.c. @yukinying

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yukinying** [comment]
Looks good.

**Comment by maditya** [comment]
:+1:

**Pull request merged**
